load("@rules_python//python:py_binary.bzl", "py_binary")
load("@rules_shell_extra//shell:rules.bzl", "sh_binary")

package(default_visibility = ["//visibility:public"])

sh_binary(
    name = "files",
    main = "files.sh",
)

sh_binary(
    name = "lines",
    data = [":files"],
    main = "lines.sh",
)

py_binary(
    name = "branches_cleanup",
    srcs = ["branches-cleanup.py"],
    main = "branches-cleanup.py",
)
